[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[workspace.dependencies]
ash = { version = "0.37.3", default-features = false, features = ["linked","debug"]}

[workspace]
members = [
    "nexodia",
    "utils"
]