[package]
name = "nexodia"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu_text = "0.8.3"

winit = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }

engine = { path = "../engine" }