[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.16.0"
serde = { version = "1.0.174", default_features = false, features = ["derive"] }
serde_json = "1.0.103"
gltf = "1.2.0"
zstd = "0.12.4"