[package]
name = "utils"
version = "0.1.0"
authors = ["muriel guedes pucci berehulka <murielguedes@pm.me>"]
edition = "2021"

[dependencies]
log = "0.4.19"
backtrace = "0.3.68"
chrono = "0.4.26"
native-dialog = "0.6.4"